"""create_refills_table

Revision ID: 15181494ad9c
Revises: f2178fe8f0ec
Create Date: 2026-05-24 01:54:22.681947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15181494ad9c'
down_revision: Union[str, Sequence[str], None] = 'f2178fe8f0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('refill_date', sa.Date(), nullable=False),
    sa.Column('contact_status', sa.Enum('pending', 'contacted', name='contactstatus'), nullable=False),
    sa.Column('refill_status', sa.Enum('pending', 'completed', 'overdue', name='refillstatus'), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refills_patient_id'), 'refills', ['patient_id'], unique=False)
    op.create_index(op.f('ix_refills_visit_id'), 'refills', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refills_visit_id'), table_name='refills')
    op.drop_index(op.f('ix_refills_patient_id'), table_name='refills')
    op.drop_table('refills')
    # ### end Alembic commands ###
