"""refactor_refills_sig_structured_fields

Revision ID: 28fb9e462fe2
Revises: 575fb65d16da
Create Date: 2026-05-25 10:06:46.609481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fb9e462fe2'
down_revision: Union[str, Sequence[str], None] = '575fb65d16da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refills', sa.Column('dose_amount', sa.Float(), nullable=True))
    op.add_column('refills', sa.Column('dose_unit', sa.String(), nullable=True))
    op.add_column('refills', sa.Column('route', sa.String(), nullable=True))
    op.add_column('refills', sa.Column('frequency_code', sa.String(), nullable=True))
    op.add_column('refills', sa.Column('duration_amount', sa.Integer(), nullable=True))
    op.add_column('refills', sa.Column('duration_unit', sa.String(), nullable=True))
    op.add_column('refills', sa.Column('total_quantity', sa.Integer(), nullable=True))
    op.add_column('refills', sa.Column('instructions', sa.Text(), nullable=True))
    op.drop_column('refills', 'dose')
    op.drop_column('refills', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refills', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('refills', sa.Column('dose', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('refills', 'instructions')
    op.drop_column('refills', 'total_quantity')
    op.drop_column('refills', 'duration_unit')
    op.drop_column('refills', 'duration_amount')
    op.drop_column('refills', 'frequency_code')
    op.drop_column('refills', 'route')
    op.drop_column('refills', 'dose_unit')
    op.drop_column('refills', 'dose_amount')
    # ### end Alembic commands ###
