"""add_recurrence_fields_to_refills

Revision ID: 575fb65d16da
Revises: 15181494ad9c
Create Date: 2026-05-24 13:50:29.612355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575fb65d16da'
down_revision: Union[str, Sequence[str], None] = '15181494ad9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refills', sa.Column('is_recurrent', sa.Boolean(), nullable=True))
    op.add_column('refills', sa.Column('recurrence_interval_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refills', 'recurrence_interval_days')
    op.drop_column('refills', 'is_recurrent')
    # ### end Alembic commands ###
