"""realign_models_visit_centric

Revision ID: 97a456b8bf3b
Revises: 52a219723e3e
Create Date: 2026-05-17 14:11:10.148452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97a456b8bf3b'
down_revision: Union[str, Sequence[str], None] = '52a219723e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop FK constraints before dropping referenced tables
    op.drop_constraint(op.f('notifications_medication_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'medication_id')
    op.drop_table('medications')
    op.drop_table('vitals')
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.add_column('patients', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('state', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('city', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('occupation', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('genotype', sa.String(), nullable=True))

    # Backfill first_name / last_name from existing full_name (split on first space)
    op.execute(
        "UPDATE patients SET first_name = SPLIT_PART(full_name, ' ', 1), "
        "last_name = SUBSTRING(full_name FROM POSITION(' ' IN full_name) + 1) "
        "WHERE full_name IS NOT NULL AND full_name != ''"
    )
    # Fallback for single-word names
    op.execute(
        "UPDATE patients SET first_name = full_name, last_name = full_name "
        "WHERE first_name IS NULL AND full_name IS NOT NULL"
    )
    # Backfill date_of_birth from dob
    op.execute(
        "UPDATE patients SET date_of_birth = dob WHERE dob IS NOT NULL"
    )

    op.alter_column('patients', 'first_name', nullable=False)
    op.alter_column('patients', 'last_name', nullable=False)
    op.alter_column('patients', 'date_of_birth', nullable=False)

    # Convert text allergies to JSONB arrays
    op.execute(
        "UPDATE patients SET allergies = CASE "
        "WHEN allergies IS NULL OR TRIM(allergies) = '' THEN '[]'::jsonb "
        "ELSE to_jsonb(string_to_array(TRIM(allergies), ', ')) END"
    )
    op.alter_column('patients', 'allergies',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='allergies::jsonb')
    # Convert text chronic_conditions to JSONB arrays
    op.execute(
        "UPDATE patients SET chronic_conditions = CASE "
        "WHEN chronic_conditions IS NULL OR TRIM(chronic_conditions) = '' THEN '[]'::jsonb "
        "ELSE to_jsonb(string_to_array(TRIM(chronic_conditions), ', ')) END"
    )
    op.alter_column('patients', 'chronic_conditions',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='chronic_conditions::jsonb')
    op.drop_constraint(op.f('patients_phone_key'), 'patients', type_='unique')
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.drop_column('patients', 'full_name')
    op.drop_column('patients', 'dob')
    op.drop_column('patients', 'is_active')
    op.add_column('visits', sa.Column('visit_number', sa.Integer(), nullable=True))
    # Backfill visit_number for existing visits
    op.execute(
        "UPDATE visits SET visit_number = sub.rn FROM "
        "(SELECT id, ROW_NUMBER() OVER (PARTITION BY patient_id ORDER BY visit_date, created_at) AS rn FROM visits) sub "
        "WHERE visits.id = sub.id"
    )
    op.alter_column('visits', 'visit_number', nullable=False)
    op.execute(
        "DO $$ BEGIN "
        "CREATE TYPE visitstatus AS ENUM ('active', 'completed', 'follow_up_pending', 'referred'); "
        "EXCEPTION WHEN duplicate_object THEN null; "
        "END $$;"
    )
    op.add_column('visits', sa.Column('status', sa.Enum('active', 'completed', 'follow_up_pending', 'referred', name='visitstatus'), nullable=True))
    # Backfill status for existing visits (assume completed since they were created before this migration)
    op.execute("UPDATE visits SET status = 'completed' WHERE status IS NULL")
    op.alter_column('visits', 'status', nullable=False)
    op.add_column('visits', sa.Column('chief_complaints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('medication_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('vitals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('clinical_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('medications_dispensed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('counselling_advice', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('follow_up', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('referral', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('visits', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visits_staff_id'), 'visits', ['staff_id'], unique=False)
    op.drop_column('visits', 'notes')
    op.drop_column('visits', 'follow_up_date')
    op.drop_column('visits', 'complaint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tables before creating FK constraints that reference them
    op.create_table('vitals',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blood_pressure_systolic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('blood_pressure_diastolic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('glucose', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spo2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('vitals_visit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vitals_pkey'))
    )
    op.create_table('medications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('drug_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('prescribed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dispensed_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('next_refill_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('medications_patient_id_fkey')),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name=op.f('medications_visit_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('medications_pkey'))
    )
    op.add_column('visits', sa.Column('complaint', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('visits', sa.Column('follow_up_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('visits', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_visits_staff_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_column('visits', 'updated_at')
    op.drop_column('visits', 'referral')
    op.drop_column('visits', 'follow_up')
    op.drop_column('visits', 'counselling_advice')
    op.drop_column('visits', 'medications_dispensed')
    op.drop_column('visits', 'clinical_assessment')
    op.drop_column('visits', 'test_results')
    op.drop_column('visits', 'vitals')
    op.drop_column('visits', 'medication_history')
    op.drop_column('visits', 'chief_complaints')
    op.drop_column('visits', 'status')
    op.execute("DROP TYPE IF EXISTS visitstatus")
    op.drop_column('visits', 'visit_number')
    # Convert JSONB arrays back to comma-separated text
    op.execute(
        "UPDATE patients SET chronic_conditions = "
        "array_to_string(ARRAY(SELECT jsonb_array_elements_text(chronic_conditions)), ', ') "
        "WHERE chronic_conditions IS NOT NULL AND jsonb_typeof(chronic_conditions) = 'array'"
    )
    op.alter_column('patients', 'chronic_conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.execute(
        "UPDATE patients SET allergies = "
        "array_to_string(ARRAY(SELECT jsonb_array_elements_text(allergies)), ', ') "
        "WHERE allergies IS NOT NULL AND jsonb_typeof(allergies) = 'array'"
    )
    op.alter_column('patients', 'allergies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('patients', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # Reconstruct full_name and dob from new columns before dropping them
    op.execute(
        "UPDATE patients SET full_name = TRIM(first_name || ' ' || last_name), "
        "dob = date_of_birth "
        "WHERE first_name IS NOT NULL"
    )
    op.alter_column('patients', 'full_name', nullable=False)
    op.alter_column('patients', 'dob', nullable=False)
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.create_unique_constraint(op.f('patients_phone_key'), 'patients', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('patients', 'genotype')
    op.drop_column('patients', 'occupation')
    op.drop_column('patients', 'city')
    op.drop_column('patients', 'state')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'last_name')
    op.drop_column('patients', 'first_name')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_column('notifications', 'updated_at')
    op.add_column('notifications', sa.Column('medication_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notifications_medication_id_fkey'), 'notifications', 'medications', ['medication_id'], ['id'])
    # ### end Alembic commands ###
