"""add fcm_token to staff and notification_log table

Revision ID: ca917079b728
Revises: 28fb9e462fe2
Create Date: 2026-05-31 19:12:44.470090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca917079b728'
down_revision: Union[str, Sequence[str], None] = '28fb9e462fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('refill', 'followup', name='notificationlogtype'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_patient_id'), 'notification_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_staff_id'), 'notification_logs', ['staff_id'], unique=False)
    op.add_column('staff', sa.Column('fcm_token', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('device_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'device_type')
    op.drop_column('staff', 'fcm_token')
    op.drop_index(op.f('ix_notification_logs_staff_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_patient_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
