"""add_cascade_delete_to_refills

Revision ID: edaf6ce972d1
Revises: ca917079b728
Create Date: 2026-06-08 01:23:09.862166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edaf6ce972d1'
down_revision: Union[str, Sequence[str], None] = 'ca917079b728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('refills_visit_id_fkey'), 'refills', type_='foreignkey')
    op.create_foreign_key(None, 'refills', 'visits', ['visit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refills', type_='foreignkey')
    op.create_foreign_key(op.f('refills_visit_id_fkey'), 'refills', 'visits', ['visit_id'], ['id'])
    # ### end Alembic commands ###
